#ifndef LV_FONTS_THAI_H
#define LV_FONTS_THAI_H

#include "lvgl.h"

/* Noto Sans Thai – generated by lv_font_conv, covers ASCII + Thai (0x0E00-0x0E7F)
 * + pre-composed cluster glyphs in the PUA range (0xE001-0xE0FF) used by the
 * thai_shaping layer for correct 2-tier diacritic stacking. */
extern const lv_font_t lv_font_noto_thai_14;
extern const lv_font_t lv_font_noto_thai_16;
extern const lv_font_t lv_font_noto_thai_20;
extern const lv_font_t lv_font_noto_thai_24;
extern const lv_font_t lv_font_noto_thai_28;

#endif /* LV_FONTS_THAI_H */
